version: "3.9"

services:
  client:
    build:
      context: ./client
      target: production
    volumes:
      - client-build:/app/.next
  server:
    build:
      context: ./server
      target: production
    volumes:
      - server-build:/app/dist

volumes:
  client-build:
  server-build:
